x1 = float(input("Enter X coordinate of first point: "))
y1 = float(input("Enter Y coordinate of first point: "))
x2 = float(input("Enter X coordinate of second point: "))
y2 = float(input("Enter Y coordinate of second point: "))
print(f"Distance between ({x1}, {y1}) and ({x2}, {y2}) points is {(((x1 - x2) ** 2) + ((y1 - y2) ** 2)) ** 0.5:.3f}")
