from aiogram import types

calc_kb = types.InlineKeyboardMarkup(row_width=4)
button1 = types.InlineKeyboardButton(text=f'', callback_data='no')
button2 = types.InlineKeyboardButton(text=f'C', callback_data='C')
button3 = types.InlineKeyboardButton(text=f'<=', callback_data='<=')
button4 = types.InlineKeyboardButton(text=f'{chr(247)}', callback_data='/')
button5 = types.InlineKeyboardButton(text=f'7', callback_data='7')
button6 = types.InlineKeyboardButton(text=f'8', callback_data='8')
button7 = types.InlineKeyboardButton(text=f'9', callback_data='9')
button8 = types.InlineKeyboardButton(text=f'{chr(215)}', callback_data='*')
button9 = types.InlineKeyboardButton(text=f'4', callback_data='4')
button10 = types.InlineKeyboardButton(text=f'5', callback_data='5')
button11 = types.InlineKeyboardButton(text=f'6', callback_data='6')
button12 = types.InlineKeyboardButton(text=f'{chr(8722)}', callback_data='-')
button13 = types.InlineKeyboardButton(text=f'1', callback_data='1')
button14 = types.InlineKeyboardButton(text=f'2', callback_data='2')
button15 = types.InlineKeyboardButton(text=f'3', callback_data='3')
button16 = types.InlineKeyboardButton(text=f'{chr(43)}', callback_data='+')
button17 = types.InlineKeyboardButton(text=f'', callback_data='no')
button18 = types.InlineKeyboardButton(text=f'0', callback_data='0')
button19 = types.InlineKeyboardButton(text=f',', callback_data='.')
button20 = types.InlineKeyboardButton(text=f'{chr(61)}', callback_data='=')
calc_kb.add(button1, button2, button3, button4, button5, button6, button7, button8, button9, button10, button11,
            button12, button13, button14, button15, button16, button17, button18, button19, button20)
